struct stat;

// system calls
int fork(void);
int exit(int) __attribute__((noreturn));
int wait(int*);
int pipe(int*);
int write(int, const void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(const char*, char**);
int open(const char*, int);
int mknod(const char*, short, short);
int unlink(const char*);
int fstat(int fd, struct stat*);
int link(const char*, const char*);
int mkdir(const char*);
int chdir(const char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);
int getyear(void);
int freemem(void);

// ulib.c
int stat(const char*, struct stat*);
char* strcpy(char*, const char*);
void *memmove(void*, const void*, int);
char* strchr(const char*, char c);
int strcmp(const char*, const char*);
void fprintf(int, const char*, ...);
void printf(const char*, ...);
char* gets(char*, int max);
uint strlen(const char*);
void* memset(void*, int, uint);
void* wf_malloc(uint);
void wf_free(void*);
void* bf_malloc(uint);
void bf_free(void*);
void* malloc(uint);
void free(void*);
void get_memory_fragments();
void wf_get_memory_fragments();
void bf_get_memory_fragments();
void ff_free(void *ptr);
void *ff_malloc(unsigned nbytes);
void ff_get_memory_fragments();
void cff_free(void *ptr);
void *cff_malloc(unsigned nbytes);
void cff_get_memory_fragments();
int atoi(const char*);
int memcmp(const void *, const void *, uint);
void *memcpy(void *, const void *, uint);
